[package]
name = "zed-glsl-extended"
version = "0.1.5"
edition = "2024"
authors = ["Semih Ozdemir <semihozdmirr@gmail.com>"]
description = "Zed GLSL Extended: glsl_analyzer LSP + glslangValidator diagnostics for OpenGL 4.6"
license = "MIT"
repository = "https://github.com/zyr1on/zed-glsl-extended"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"