id = "glsl-extended"
name = "GLSL Extended"
description = "High-performance GLSL LSP for Zed: syntax highlighting, compile diagnostics (glslangValidator), smart autocomplete with snippets, signature help, hover docs, formatting, and goto definition."
version = "0.1.11"
schema_version = 1
authors = ["Semih Ozdemir <semihozdmirr@gmail.com>"]
repository = "https://github.com/zyr1on/zed-glsl-extended"

languages = ["languages/glsl"]

[language_servers.glsl_validator]
name = "GLSL Validator LSP"
language = "GLSL"

[grammars.glsl]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-glsl"
commit = "24a6c8ef698e4480fecf8340d771fbcb5de8fbb4"